export enum TweenType {
    LINEAR = "linear",
    EASE_IN_QUAD = "easeInQuad",
    EASE_OUT_QUAD = "easeOutQuad",
    EASE_IN_OUT_QUAD = "easeInOutQuad",
    EASE_IN_CUBIC = "easeInCubic",
    EASE_OUT_CUBIC = "easeOutCubic",
    EASE_IN_OUT_CUBIC = "easeInOutCubic",
    EASE_IN_QUART = "easeInQuart",
    EASE_OUT_QUART = "easeOutQuart",
    EASE_IN_OUT_QUART = "easeInOutQuart",
    EASE_IN_QUINT = "easeInQuint",
    EASE_OUT_QUINT = "easeOutQuint",
    EASE_IN_OUT_QUINT = "easeInOutQuint",
    EASE_IN_SINE = "easeInSine",
    EASE_OUT_SINE = "easeOutSine",
    EASE_IN_OUT_SINE = "easeInOutSine",
    EASE_IN_EXPO = "easeInExpo",
    EASE_OUT_EXPO = "easeOutExpo",
    EASE_IN_OUT_EXPO = "easeInOutExpo",
    EASE_IN_CIRC = "easeInCirc",
    EASE_OUT_CIRC = "easeOutCirc",
    EASE_IN_OUT_CIRC = "easeInOutCirc",
}
export const TweenTypes = [
    TweenType.LINEAR,
    TweenType.EASE_IN_QUAD,
    TweenType.EASE_OUT_QUAD,
    TweenType.EASE_IN_OUT_QUAD,
    TweenType.EASE_IN_CUBIC,
    TweenType.EASE_OUT_CUBIC,
    TweenType.EASE_IN_OUT_CUBIC,
    TweenType.EASE_IN_QUART,
    TweenType.EASE_OUT_QUART,
    TweenType.EASE_IN_OUT_QUART,
    TweenType.EASE_IN_QUINT,
    TweenType.EASE_OUT_QUINT,
    TweenType.EASE_IN_OUT_QUINT,
    TweenType.EASE_IN_SINE,
    TweenType.EASE_OUT_SINE,
    TweenType.EASE_IN_OUT_SINE,
    TweenType.EASE_IN_EXPO,
    TweenType.EASE_OUT_EXPO,
    TweenType.EASE_IN_OUT_EXPO,
    TweenType.EASE_IN_CIRC,
    TweenType.EASE_OUT_CIRC,
    TweenType.EASE_IN_OUT_CIRC,
];
export default TweenType;